//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdditionTask
{
    using System.Data.Entity;

    public partial class ModelEntityContainer : DbContext
    {
        public ModelEntityContainer()
            : base("name=ModelEntityContainer")
        {
        }
  
        public virtual DbSet<MyTable> MyTables { get; set; }
    }
}
